name: Docker Image CI

on:
  push:
    tags:
      - v*.*.*
      - latest
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      env:
        VERSION: ${{ steps.vars.outputs.tag }}
      run: |
          docker build . --file Dockerfile --tag ghcr.io/fixhack/dctm-postgresql:$VERSION
          docker push ghcr.io/fixhack/dctm-postgresql:$VERSION